### ISSUE TITLE
Remove cmd/pulumi-gen-xyz in favor of pulumi package gen-sdk

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi-component-provider-py-boilerplate#45]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

This moves complexity out of the boilerplate repo. An example PR that did this is https://github.com/pulumi/pulumi-pulumiservice/pull/240.

**Comment by ebob9** [comment]
Hi @iwahbe,

I was trying to understand writing pulumi provider / components, and I noticed the current `main` branch doesn't work out of the box. It appears to be related to pulumi/pulumi-component-provider-py-boilerplate#40 and this issue #45. 

In order to get it working for me, I decided to make the following updates:
1. Port your changes for `pulumi package gen-sdk` over from pulumi/pulumi-pulumiservice#240 (fixes this #45 issue.)
2. Update the `pulumi` version from `v3.30.0` ->`v3.116.1` (current latest release, and also fixes pulumi/pulumi-component-provider-py-boilerplate#40.)
3. Update the `pulumi-aws` provider from `v5.3.0` -> `v6.37.0` (current latest release)
4. Delete/remove `pulumi-gen-xyz` directory and related files.

After the changes, I could successfully build/deploy the example in the `README.md`.

This was a great exercise for me on learning how pulumi and providers/components work. I'm not familiar with your pull request process / contribution requirements, but I'll open a pull request in case the updates will help you or others out. Thanks!

**Comment by iwahbe** [comment]
Hey @ebob9. Thanks for writing up your experience and submitting the PR! I'm glad you found it educational. I took a cursory look at your PR, and it certainly looks like it will help others (and make this repo better).

I'll take a deeper look later today and either get it merged or give feedback before tomorrow.
